@startuml ms-container
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

skinparam wrapWidth 300
LAYOUT_WITH_LEGEND()

title Диаграмма конейнеров для системы Теплый дом

Person(user, "Пользователь", "Управляет устройствами и просматривает телеметрию через веб-интерфейс.")
Person(device, "Устройство умного дома", "Отопления, ворота, освещение и тд")

System_Boundary(ecosystem, "Экосистема умного дома") {
    Container(device_management, "Управления приборами умного дома", "Управлление отоплением, воротами, освещением и тд")
    Container(monitoring_telemetry, "Управление данных телеметрии и мониторинг", "Сбор данных с устройств, хранение и просмотр данных")
    Container(parner_integration, "Управление подключением и настройки новых устройств", "Поддержка стандарта и протокола подключения новых устройств, первичная настройка и подключение новых устройств")
    Container(user_interface, "Веб-интерфейс пользователя", "Веб-интерфейс для управления устройствами и просмотра телеметрии")
    Container(api_gateway, "API Gateway")
    ContainerQueue(kafka, "Шина данных", "Очередь команд и запросов")
}

Rel(user, user_interface, "Управление и настройка устройста, просмотр телеметрии")
Rel(user_interface, api_gateway, "")
Rel(device, api_gateway, "Передача данных телеметрии")
Rel(api_gateway, kafka, "Отправка команд и запросов")
Rel(kafka, monitoring_telemetry, "Данные телеметрии")
Rel(kafka, device_management, "Команды управления и настройки устройств")
Rel(kafka, parner_integration, "Подключение и настройка устройства")

@enduml